development:
  adapter: postgresql
  encoding: unicode
  database: carmart_development
  pool: 5
  host: localhost
  username: matt
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: carmart_test
  pool: 5
  host: localhost
  username: matt
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: carmart_production
  pool: 5
  host: localhost
  username: matt
  password:
